export const LOAD_CARS_SUCCESS = "LOAD_CARS_SUCCESS";
export const LOAD_CARS_FAILURE = "LOAD_CARS_FAILURE";
export const LOAD_CARS_PENDING = "LOAD_CARS_PENDING";

export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_FAILURE = "ADD_CAR_FAILURE";
export const ADD_CAR_PENDING = "ADD_CAR_PENDING";

export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_FAILURE = "DELETE_CAR_FAILURE";
export const DELETE_CAR_PENDING = "DELETE_CAR_PENDING";

export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const EDIT_CAR_FAILURE = "EDIT_CAR_FAILURE";
export const EDIT_CAR_PENDING = "EDIT_CAR_PENDING";

export const LOAD_LOCATIONS_SUCCESS = "LOAD_LOCATIONS_SUCCESS";
export const LOAD_LOCATIONS_FAILURE = "LOAD_LOCATIONS_FAILURE";
export const LOAD_LOCATIONS_PENDING = "LOAD_LOCATIONS_PENDING";

export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";
export const ADD_LOCATION_PENDING = "ADD_LOCATION_PENDING";

export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILURE = "DELETE_LOCATION_FAILURE";
export const DELETE_LOCATION_PENDING = "DELETE_LOCATION_PENDING";

export const EDIT_LOCATION_SUCCESS = "EDIT_LOCATION_SUCCESS";
export const EDIT_LOCATION_FAILURE = "EDIT_LOCATION_FAILURE";
export const EDIT_LOCATION_PENDING = "EDIT_LOCATION_PENDING";
